### ISSUE TITLE
Add resharper support

### ISSUE THREAD

**Issue by leddt** [leddt/visualstudio-colors-solarized#1]

**Comment by joce** [comment]
Could you provide a link? Looking at @brantb 's [repo](https://github.com/brantb/solarized), I can't find anything about ReSharper.

**Comment by leddt** [comment]
Hi @joce, ReSharper support has been merged into this repo (pull request #3). 

However please be aware that this project is no longer actively maintained. ReSharper support is probably incomplete with newer versions. I still accept pull requests if you want to contribute.
