### ISSUE TITLE
VS2013 theme in VS15 - parens, braces, brackets do not get colors set with solarized dark theme

### ISSUE THREAD

**Issue by caseyjmorris** [leddt/visualstudio-colors-solarized#31]
As a result of this, if you import the solarized dark settings while you have the theme set to "light" or "blue" they are black on the dark-blue background and very hard to read.  If you set it to the dark theme before importing they'll be white, which is OK.

**Comment by leddt** [comment]
Thanks for reporting. I don't really maintain the color scheme since VS ships with a nice dark theme, but I will happily merge a pull request addressing the issue.

**Comment by styfle** [comment]
There is also the official Microsoft extension but it seems to have some bugs in 2015 too: https://visualstudiogallery.msdn.microsoft.com/6f4b51b6-5c6b-4a81-9cb5-f2daa560430b

**Comment by mloskot** [comment]
ATM, Microsoft's extension ships broken Solarized Dark for VS2015. Someone has released corrected version of Microsoft's Solarized Dark here https://github.com/lyphtec/solarized
