### ISSUE TITLE
file is not a valid .vssettings file

### ISSUE THREAD

**Issue by clarity99** [leddt/visualstudio-colors-solarized#40]
I've cloned the repo and when I try to import either dark or light file into vs2017 I get this:

The settings in file 'C:\VSS\src\Customer\TKM\solarized-dark.vssettings' cannot be imported because this file is not a valid .vssettings file.

vs 14.0.25431.01 Update 3

**Comment by leddt** [comment]
Interesting. I wonder if it's caused by the VS Update? Do you have the time to debug this?

**Comment by clarity99** [comment]
sure, what can I do?

**Comment by leddt** [comment]
Hey just checking, you say your VS version is 14.0. Unless I'm mistaken this is VS2015, yet you mention VS2017 in your first sentence. Are you sure you are using the correct version of the vssettings ?

**Comment by clarity99** [comment]
ugh, I did have the wrong vs open :( It actually works fine, when I import it from VS17. Sheesh!
