### ISSUE TITLE
Why special focus for jQuery Id selector?

### ISSUE THREAD

**Issue by kumarvikram** [leddt/visualstudio-colors-solarized#41]
Why it is highlighting a jQuery Id selector like this?
![image](https://user-images.githubusercontent.com/5526914/31285046-e17f9890-aad7-11e7-9ca5-1482dc9de9bb.png)

**Comment by leddt** [comment]
This is most likely a new highlighting option that the theme doesn't support directly.

We would need to figure out what is the missing setting and add it to the themes with an appropriate color.
