### ISSUE TITLE
Cannot import settings

### ISSUE THREAD

**Issue by davidmn** [leddt/visualstudio-colors-solarized#47]
Running  Visual Studio Enterprise 2017 version 15.7.1

Importing the vssetings files gives the following error:
"The settings in file C:\Users\...\solarized-dark.vssettings" cannot be imported because this file is not a valid .vssettings fil."

Visual Studio does not provide any debugging information.

**Comment by jpeart03** [comment]
Open the vssettings file you downloaded to make sure you didn't save the page's HTML as a file.

To get the raw _dark_ vssettings file:

1. Navigate to: [visualstudio-colors-solarized/vs2017/solarized-dark.vssettings](url)
1.  click the **Raw** button
1. right-click anywhere on the raw code and "save as..." to a known location
1. Import settings to Visual Studio

**Comment by davidmn** [comment]
Ok that seems to work apart from it only changes the colour in the text editor. All other panes remain default. Is that the expected behaviour?

**Comment by davidmn** [comment]
Thanks @jpeart03, that's does what I want.
